<?php
/**
 * Created by IntelliJ IDEA.
 * User: Nikolay Chervyakov 
 * Date: 01.10.2014
 * Time: 14:41
 */


namespace App\Rest\Controller;


use App\Rest\Controller;

class Product extends Controller
{
    public function action_get_collection()
    {
        $ids = $this->request->get($this->model->id_field);
        if ($ids) {
            $ids = array_unique(preg_split('/\s*,\s*/', $ids, -1, PREG_SPLIT_NO_EMPTY));
            if (count($ids) > 0) {
                $this->model->where($this->model->id_field, 'IN', $this->pixie->db->expr('(' . implode(',', $ids) . ')'));
            }
        }
        return parent::action_get_collection(); // TODO: Change the autogenerated stub
    }
} 